In [1]:
import pandas as pd
import json 
import numpy as np

In [37]:
from pandarallel import pandarallel
pandarallel.initialize()

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [2]:
real_gdp_r = pd.read_csv('/home/yiyi/Documents/MigrationsKB/eurostat_stats/csv/real_gdp_growth_rate.csv',
                         index_col=0)
unemployment_rate = pd.read_csv('/home/yiyi/Documents/MigrationsKB/eurostat_stats/csv/unemployment_rate.csv',
                                index_col=0)
youth_unemployment_rate = pd.read_csv(
    '/home/yiyi/Documents/MigrationsKB/eurostat_stats/csv/youth_unemployment_rate.csv', index_col=0)

In [6]:
rgdpr = real_gdp_r.to_dict()

In [7]:
rgdpr['AT'][2013]

0.0

In [104]:
df = pd.read_csv('input/migrationsKB_uuid.csv', low_memory=False)

In [106]:
df.iloc[177090]

tokens               ['leavealighton', 'european', 'proud', 'scotla...
topics                                                    [34, 48, 32]
id                                                 1344786415004119040
texts                I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...
hashtags             ['LeaveALightOn', 'ScotlandInEurope', 'IndySco...
entities                                                            []
urls                                                                []
processed_tokens     ['proud', 'european', 'leavealighton', 'scotla...
processed_text       proud european leavealighton scotlandineurope ...
processed_tm                              [22302, 15969, 15826, 24352]
text_processed       proud european leavealighton scotlandineurope ...
pred_sentiment                                                       2
hatespeech_pred                                                      0
hatespeech_label                                                normal
sentiment_label                                               positive
Year                                                              2020
author_id                                          1292760397007802368
Month                                                               12
Day                                                                 31
entity_0                                                           NaN
entity_1                                                           NaN
entity_2                                                           NaN
entity_3                                                           NaN
entity_4                                                           NaN
entity_5                                                           NaN
entity_6                                                           NaN
entity_7                                                           NaN
entity_8                                                           NaN
entity_9                                                           NaN
entity_10                                                          NaN
entity_11                                                          NaN
entity_12                                                          NaN
entity_13                                                          NaN
entity_14                                                          NaN
entity_15                                                          NaN
entity_16                                                          NaN
entity_17                                                          NaN
entity_18                                                          NaN
entity_19                                                          NaN
entity_20                                                          NaN
entity_21                                                          NaN
country_code                                                        GB
lon                                                           -5.43206
lat                                                           56.03796
created_at                                    2020-12-31T23:24:00.000Z
place_fullname0                                 Lochgilphead, Scotland
pred_country_name                                                  GBR
consistent                                                        True
place_id                                              096b2dd33b187265
place_fullname                                  Lochgilphead, Scotland
twi_long                                                           NaN
twi_lat                                                            NaN
user_mentions                                                       []
retweet_count                                                     36.0
reply_count                                                        0.0
like_count                                                        44.0
quote_count                                                        0.0
id_gen                                2018d6ea3285487d9cd1259122af2b46
author_id_gen                         a639a9f328bc4f8f8de0782341534ec8
prim_topic                                                          34
Name: 177090, dtype: object

In [41]:
df.columns

Index(['tokens', 'topics', 'id', 'texts', 'hashtags', 'entities', 'urls',
       'processed_tokens', 'processed_text', 'processed_tm', 'text_processed',
       'pred_sentiment', 'hatespeech_pred', 'hatespeech_label',
       'sentiment_label', 'Year', 'author_id', 'Month', 'Day', 'entity_0',
       'entity_1', 'entity_2', 'entity_3', 'entity_4', 'entity_5', 'entity_6',
       'entity_7', 'entity_8', 'entity_9', 'entity_10', 'entity_11',
       'entity_12', 'entity_13', 'entity_14', 'entity_15', 'entity_16',
       'entity_17', 'entity_18', 'entity_19', 'entity_20', 'entity_21',
       'country_code', 'pred_lon', 'pred_lat', 'created_at',
       'pred_country_name', 'consistent', 'place_id', 'place_fullname',
       'twi_long', 'twi_lat', 'user_mentions', 'retweet_count', 'reply_count',
       'like_count', 'quote_count', 'id_gen', 'author_id_gen', 'prim_topic'],
      dtype='object')

In [99]:
lon= df.loc[1344786415004119040]['twi_long']

In [100]:
np.isnan(lon)

True

In [101]:
df.loc[1344786415004119040]['consistent']

True

In [103]:
df.loc[1344786415004119040]

tokens               ['leavealighton', 'european', 'proud', 'scotla...
topics                                                    [34, 48, 32]
id                                                 1344786415004119040
texts                I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...
hashtags             ['LeaveALightOn', 'ScotlandInEurope', 'IndySco...
entities                                                            []
urls                                                                []
processed_tokens     ['proud', 'european', 'leavealighton', 'scotla...
processed_text       proud european leavealighton scotlandineurope ...
processed_tm                              [22302, 15969, 15826, 24352]
text_processed       proud european leavealighton scotlandineurope ...
pred_sentiment                                                       2
hatespeech_pred                                                      0
hatespeech_label                                                normal
sentiment_label                                               positive
Year                                                              2020
author_id                                          1292760397007802368
Month                                                               12
Day                                                                 31
entity_0                                                           NaN
entity_1                                                           NaN
entity_2                                                           NaN
entity_3                                                           NaN
entity_4                                                           NaN
entity_5                                                           NaN
entity_6                                                           NaN
entity_7                                                           NaN
entity_8                                                           NaN
entity_9                                                           NaN
entity_10                                                          NaN
entity_11                                                          NaN
entity_12                                                          NaN
entity_13                                                          NaN
entity_14                                                          NaN
entity_15                                                          NaN
entity_16                                                          NaN
entity_17                                                          NaN
entity_18                                                          NaN
entity_19                                                          NaN
entity_20                                                          NaN
entity_21                                                          NaN
country_code                                                        GB
pred_lon                                                      -5.43206
pred_lat                                                      56.03796
created_at                                    2020-12-31T23:24:00.000Z
pred_country_name                                                  GBR
consistent                                                        True
place_id                                              096b2dd33b187265
place_fullname                                  Lochgilphead, Scotland
twi_long                                                           NaN
twi_lat                                                            NaN
user_mentions                                                       []
retweet_count                                                     36.0
reply_count                                                        0.0
like_count                                                        44.0
quote_count                                                        0.0
id_gen                                2018d6ea3285487d9cd1259122af2b46
author_id_gen                         a639a9f328bc4f8f8de0782341534ec8
prim_topic                                                          34
Name: 1344786415004119040, dtype: object

In [96]:
np.float(lon)==np.nan

<ipython-input-96-285b925f813f>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(lon)==np.nan

False

In [107]:
df.rename(columns={'lat':'pred_lat', 'lon':'pred_lon'}, inplace=True)

In [108]:
df.drop(columns=['place_fullname0'], inplace=True)

In [110]:
df.to_csv('input/migrationsKB_uuid.csv', index=False)

In [33]:
# df.index=df.id

In [88]:
twi_long_list = df['twi_long']

In [90]:
df

,tokens,topics,id,texts,hashtags,entities,urls,processed_tokens,processed_text,processed_tm,...,twi_long,twi_lat,user_mentions,retweet_count,reply_count,like_count,quote_count,id_gen,author_id_gen,prim_topic
id,,,,,,,,,,,,,,,,,,,,,
285908615561363456,"['missed', 'beginning', 'aching', 'notice', 'y...","[12, 48, 32]",285908615561363456,"Completely missed the New Year beginning, too ...",['cardsagainsthumanity'],[],[],"['completely', 'missed', 'new', 'year', 'begin...",completely missed new year beginning engrossed...,"[18416, 374, 16452, 4179, 24601, 15425, 17097,...",...,-1.258131,53.100616,[],0.0,0.0,0.0,0.0,3165a1219c1642959c0f220a5826dc2a,294d47783c5e4408ab129a6a93fb0a15,12
313053990902456320,"['trouble', 'call', 'cardsagainsthumanity']","[48, 17, 3]",313053990902456320,"If you're in trouble, you need to call... #car...",['cardsagainsthumanity'],[],['https://twitter.com/OperaticBacon/status/313...,"['trouble', 'need', 'cardsagainsthumanity']",trouble need cardsagainsthumanity,"[8381, 21418, 24601]",...,-1.258288,53.100615,[],0.0,0.0,0.0,0.0,a256d6d6c7ba48acbee98e1d4625802d,294d47783c5e4408ab129a6a93fb0a15,48
285915248383361026,"['awesome', 'yourewelcome']","[48, 31, 1]",285915248383361026,Damien_Sandow is awesome #YoureWelcome,['YoureWelcome'],['Damien_Sandow'],[],"['damien_sandow', 'awesome', 'yourewelcome']",damien_sandow awesome yourewelcome,"[3849, 14438]",...,-0.637335,51.917134,[],0.0,0.0,0.0,0.0,5773523185ca42ad8b13100511b044ff,dfe2c45cee5c47d9a438191428ba9370,48
285921849446117376,"['needed', 'asylum', 'ryan']","[16, 17, 48]",285921849446117376,Ryan was looking at me like I needed to be in ...,[],['Ryan'],[],"['ryan', 'looking', 'like', 'needed', 'asylum'...",ryan looking like needed asylum troublemaker came,"[21183, 3768, 11479]",...,-0.606182,52.285503,[],0.0,0.0,0.0,0.0,bae9a2b6b0ea49aab0d4df653150e92e,6ab49c01aef549b687d1780b877fc19e,16
285997288793460736,"['stuck', 'illegal', 'work', 'lol', 'partying']","[27, 40, 45]",285997288793460736,@CapitalOfficial wish I was partying.... I'm s...,['illegal'],[],[],"['wish', 'partying', 'stuck', 'work', 'illegal...",wish partying stuck work illegal lol,"[24668, 4434, 21729, 19124, 21887]",...,-0.619785,53.570898,['CapitalOfficial'],1.0,1.0,1.0,0.0,56606f959bb54df5a1330b3520907119,24e422c1212543b784dc7615a4c476a8,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344786415004119040,"['leavealighton', 'european', 'proud', 'scotla...","[34, 48, 32]",1344786415004119040,I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...,"['LeaveALightOn', 'ScotlandInEurope', 'IndySco...",[],[],"['proud', 'european', 'leavealighton', 'scotla...",proud european leavealighton scotlandineurope ...,"[22302, 15969, 15826, 24352]",...,NaN,NaN,[],36.0,0.0,44.0,0.0,2018d6ea3285487d9cd1259122af2b46,a639a9f328bc4f8f8de0782341534ec8,34
1344789100902162433,"['minute', 'wee', 'wi', 'eh', 'tae', 'whit', '...","[48, 7, 32]",1344789100902162433,2021 in a wee minute. And whit are you going t...,"['DissolveTheUnion', 'IndyScotland21', 'Scotla...",[],[],"['wee', 'minute', 'whit', 'going', 'tae', 'dae...",wee minute whit going tae dae come going disso...,"[6852, 5572, 19052, 15787, 9311, 14631, 23988,...",...,NaN,NaN,[],3.0,2.0,2.0,0.0,0565132d43714278bf7d1cad9e704f66,37b45cb033934c5c975d0c5d37deb106,48
1344790546875871237,"['iameuropean', 'star', 'heartbroken', 'bye', ...","[8, 48, 17]",1344790546875871237,"Bye bye EU, Iâ€™m am and always will be heartbro...","['BrexitDisaster', 'IAmEuropean']",[],['https://twitter.com/redlibertine/status/1344...,"['bye', 'bye', 'heartbroken', 'star', 'safe', ...",bye bye heartbroken star safe brexitdisaster i...,"[7341, 7341, 13987, 23988, 6714, 3906, 16191, ...",...,NaN,NaN,[],0.0,0.0,4.0,0.0,ea783b5215484c988065dcf9bdd5ec84,e4cab414f2be45f19b73fcc21ab0c997,8
1344791154005573632,"['amp', 'ahead', 'europe', 'hour', 'allowing',...","[4, 40, 18]",1344791154005573632,As #Europe is one hour ahead of #Britain they ...,"['Europe', 'Britain', 'celebrating', 'NewYear'...",[],[],"['europe', 'hour', 'ahead', 'britain', 'celebr...",europe hour ahead britain celebrating newyear ...,"[2878, 2885, 2530, 17344, 21333, 9278, 24558, ...",...,NaN,NaN,['Kevin_Maguire'],0.0,0.0,1.0,0.0,918058469e7d4b8f9674c3dc60383957,53dee5c37f3b4b05b48a29cb16c0bbf0,4
1344793429360959491,"['scotlandineu', 'pass', 'scotlandineurope']","[48, 10, 12]",1344793429360959491,Pass it on #IndyScotland21 #ScotlandinEU #Scot...,"['IndyScotland21', 'ScotlandinEU', 'ScotlandIn...",[],[],"['pas', 'indyscotland21', 'scotlandineu', 'sco...",pas indyscotland21 scotlandineu scotlandineuro...,"[23636, 2813, 24352]",...,NaN,NaN,[],1.0,0.0,2.0,0.0,66df93d6b0c848e2b9427bd6e137a30a,cee3dba2a4294ef0ae458849a0b08b4c,48

In [89]:
twi_long_list

id
285908615561363456    -1.258131
313053990902456320    -1.258288
285915248383361026    -0.637335
285921849446117376    -0.606182
285997288793460736    -0.619785
                         ...
1344786415004119040         NaN
1344789100902162433         NaN
1344790546875871237         NaN
1344791154005573632         NaN
1344793429360959491         NaN
Name: twi_long, Length: 177095, dtype: float64

In [48]:
df_geo = df[['pred_lat', 'pred_lon', 'consistent', 'place_fullname', 'pred_country_name', 'country_code', 'twi_long', 'twi_lat']]

In [51]:
df_geo

,pred_lat,pred_lon,consistent,place_fullname,pred_country_name,country_code,twi_long,twi_lat,lon,lat
id,,,,,,,,,,
285908615561363456,53.100616,-1.258131,True,"Ashfield, England",NaN,GB,-1.258131,53.100616,-1.258131,53.100616
313053990902456320,53.100615,-1.258288,True,"Ashfield, England",NaN,GB,-1.258288,53.100615,-1.258288,53.100615
285915248383361026,51.917134,-0.637335,True,"Central Bedfordshire, England",NaN,GB,-0.637335,51.917134,-0.637335,51.917134
285921849446117376,52.285503,-0.606182,True,"East Northamptonshire, England",NaN,GB,-0.606182,52.285503,-0.606182,52.285503
285997288793460736,53.570898,-0.619785,True,"North Lincolnshire, England",NaN,GB,-0.619785,53.570898,-0.619785,53.570898
...,...,...,...,...,...,...,...,...,...,...
1344786415004119040,56.037960,-5.432060,True,"Lochgilphead, Scotland",GBR,GB,NaN,NaN,NaN,NaN
1344789100902162433,55.949730,-3.193330,True,"Edinburgh, Scotland",GBR,GB,NaN,NaN,NaN,NaN
1344790546875871237,51.882460,4.287840,True,"Rotterdam, Niederlande",NLD,NL,NaN,NaN,NaN,NaN
1344791154005573632,NaN,NaN,True,"Witton Gilbert, England",GBR,GB,NaN,NaN,NaN,NaN
1344793429360959491,57.166670,-2.166670,True,"Aberdeen, Scotland",GBR,GB,NaN,NaN,NaN,NaN

In [60]:
df_infer = df_geo[(df_geo['lon'].isnull())| (df_geo['lat'].isnull()) & (df_geo['consistent']==True)]

In [62]:
df_infer['lat'] = df_infer['pred_lat']
df_infer['lon'] = df_infer['pred_lon']

<ipython-input-62-81a1495fba31>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_infer['lat'] = df_infer['pred_lat']
<ipython-input-62-81a1495fba31>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_infer['lon'] = df_infer['pred_lon']

,pred_lat,pred_lon,consistent,place_fullname,pred_country_name,country_code,twi_long,twi_lat,lon,lat
id,,,,,,,,,,
1231355568402685953,53.53333,-1.50000,True,"Barnsley, England",GBR,GB,NaN,NaN,-1.50000,53.53333
286566022813724672,NaN,NaN,True,NaN,NaN,GB,NaN,NaN,NaN,NaN
1110529520661078017,53.38297,-1.46590,True,"Sheffield, England",GBR,GB,NaN,NaN,-1.46590,53.38297
1141587633832939520,53.93264,-1.28712,True,"Yorkshire and The Humber, England",GBR,GB,NaN,NaN,-1.28712,53.93264
1132759770866360320,51.40148,-1.32471,True,"Newbury, England",GBR,GB,NaN,NaN,-1.32471,51.40148
...,...,...,...,...,...,...,...,...,...,...
1344786415004119040,56.03796,-5.43206,True,"Lochgilphead, Scotland",GBR,GB,NaN,NaN,-5.43206,56.03796
1344789100902162433,55.94973,-3.19333,True,"Edinburgh, Scotland",GBR,GB,NaN,NaN,-3.19333,55.94973
1344790546875871237,51.88246,4.28784,True,"Rotterdam, Niederlande",NLD,NL,NaN,NaN,4.28784,51.88246
1344791154005573632,NaN,NaN,True,"Witton Gilbert, England",GBR,GB,NaN,NaN,NaN,NaN
1344793429360959491,57.16667,-2.16667,True,"Aberdeen, Scotland",GBR,GB,NaN,NaN,-2.16667,57.16667

In [44]:
df.parallel_apply(process_geo_long)

KeyError: 'twi_long'

In [27]:
df.loc[]

tokens               ['enforcement', 'positive', 'case', 'immigrati...
topics                                                     [22, 21, 9]
id                                                  332190563354943488
texts                .@jdportes: "Miliband made sensible arguments ...
hashtags                                                            []
entities                                                  ['Miliband']
urls                                                                []
processed_tokens     ['miliband', 'sensible', 'argument', 'enforcem...
processed_text       miliband sensible argument enforcement nmw par...
processed_tm         [15389, 16539, 12861, 3457, 24555, 24210, 1653...
text_processed       miliband sensible argument enforcement nmw non...
pred_sentiment                                                       2
hatespeech_pred                                                      0
hatespeech_label                                                normal
sentiment_label                                               positive
Year                                                              2013
author_id                                                     61073310
Month                                                                5
Day                                                                  8
entity_0             {'mention': 'miliband', 'id': 394409, 'start_p...
entity_1             {'mention': 'nmw', 'id': 1819141, 'start_pos':...
entity_2                                                           NaN
entity_3                                                           NaN
entity_4                                                           NaN
entity_5                                                           NaN
entity_6                                                           NaN
entity_7                                                           NaN
entity_8                                                           NaN
entity_9                                                           NaN
entity_10                                                          NaN
entity_11                                                          NaN
entity_12                                                          NaN
entity_13                                                          NaN
entity_14                                                          NaN
entity_15                                                          NaN
entity_16                                                          NaN
entity_17                                                          NaN
entity_18                                                          NaN
entity_19                                                          NaN
entity_20                                                          NaN
entity_21                                                          NaN
country_code                                                        GB
lon                                                          -105.0372
lat                                                           39.83665
created_at                                    2013-05-08T17:49:36.000Z
place_fullname0                                   Westminster, England
pred_country_name                                                  USA
consistent                                                       False
place_id                                              548c2b8e3921a85a
place_fullname                                    Westminster, England
twi_long                                                           NaN
twi_lat                                                            NaN
user_mentions                                             ['jdportes']
retweet_count                                                      1.0
reply_count                                                        0.0
like_count                                                         0.0
quote_count                                                        0.0
id_gen                                63a75b3484f347c8b9c8ae9c68da3121
author_id_gen                         a722ce47bf75475580e8fcd87ade457b
prim_topic                                                          22
Name: 2006, dtype: object

In [26]:
df[df.consistent==False]

,tokens,topics,id,texts,hashtags,entities,urls,processed_tokens,processed_text,processed_tm,...,twi_long,twi_lat,user_mentions,retweet_count,reply_count,like_count,quote_count,id_gen,author_id_gen,prim_topic
2006,"['enforcement', 'positive', 'case', 'immigrati...","[22, 21, 9]",332190563354943488,".@jdportes: ""Miliband made sensible arguments ...",[],['Miliband'],[],"['miliband', 'sensible', 'argument', 'enforcem...",miliband sensible argument enforcement nmw par...,"[15389, 16539, 12861, 3457, 24555, 24210, 1653...",...,NaN,NaN,['jdportes'],1.0,0.0,0.0,0.0,63a75b3484f347c8b9c8ae9c68da3121,a722ce47bf75475580e8fcd87ade457b,22
2008,"['people', 'fantastic', 'making', 'case', 'pol...","[45, 4, 22]",332192551614435328,.@HackneyAbbott making fantastic case that lib...,[],[],[],"['making', 'fantastic', 'case', 'liberal', 'ec...",making fantastic case liberal economics libera...,"[8538, 4246, 11561, 15845, 13248, 15845, 12265...",...,NaN,NaN,['HackneyAbbott'],0.0,0.0,0.0,0.0,e46580e57e6e4886b27439c6c1b8702b,a722ce47bf75475580e8fcd87ade457b,45
5085,"['citizenship', 'senators', 'immigration', 'un...","[42, 22, 17]",295950859823616000,"""@sherryrehman: A new path to citizenship in t...","['US', 'immigration']",[],['http://wapo.st/Vr8nWh'],"['new', 'path', 'citizenship', 'senator', 'unv...",new path citizenship senator unveil major immi...,"[20189, 7377, 11969, 15912, 22849, 12265, 17548]",...,NaN,NaN,['sherryrehman'],0.0,0.0,0.0,0.0,898d5ecce15c4458af46d1b4e627b763,e2727f9321e441a69fc83607a2d9a895,42
6178,"['businesses', 'bowler', 'team', 'education', ...","[10, 32, 2]",1150484609513250816,Congratulations England_Cricket team:- Captain...,[],"['England_Cricket', 'NHS']",[],"['congratulation', 'england_cricket', 'team', ...",congratulation england_cricket team captained ...,"[9196, 2219, 20015, 5666, 13687, 20015, 12164,...",...,NaN,NaN,[],90.0,9.0,281.0,6.0,ec0d5349b8a44bce851a85d11ac50432,53781333f47a47839eaceb86ec2e252b,10
6610,"['topics', 'immigration', 'eu', 'sense', 'make...","[39, 17, 22]",1116433075842551809,@nejafeja @drdelusional Yep. Never ever on tv ...,[],[],[],"['yep', 'especially', 'topic', 'sense', 'topic...",yep especially topic sense topic like immigrat...,"[24251, 22104, 12012, 20373, 17929, 12012, 139...",...,NaN,NaN,"['nejafeja', 'drdelusional']",0.0,1.0,1.0,0.0,5bca062335ea4716acd758ddfdbf1657,8714c3e1f5f247ad9e0a03b7e3fb3ea6,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176875,"['extremists', 'years', 'find', 'idiocy', 'clu...","[11, 2, 45]",1341987173424361472,@RustyLoaf You'll then find a clutch of radica...,[],[],[],"['find', 'clutch', 'radical', 'right', 'wing',...",find clutch radical right wing extremist year ...,"[5835, 8177, 23358, 11335, 1968, 5718, 9466, 1...",...,NaN,NaN,['RustyLoaf'],0.0,0.0,0.0,0.0,776b3ddd84794f0abba8ca9300f13fcc,479d150be9ad41fdbdfffec1fe7a44d5,11
176908,"['shame', 'gaps', 'destroy', 'fall', 'policy',...","[22, 49, 13]",1342389580255911936,As always.. shame about the immigration polic...,[],[],['https://twitter.com/AusHCUK/status/134202054...,"['shame', 'immigration', 'policy', 'continues'...",shame immigration policy continues destroy fam...,"[5905, 12265, 12085, 19788, 8209, 14410, 11848...",...,NaN,NaN,[],0.0,0.0,0.0,0.0,e7da4930f0ec46d19da7f273673caa0f,af26816497bb40a48511ab802b6b03b1,22
176918,"['car', 'merrychristmas', 'mum', 'lovely', 'it...","[43, 48, 8]",1342596798922293248,Mum: Bukake sounds like a lovely Italian sport...,"['CardsAgainstHumanity', 'MerryChristmas']",[],[],"['mum', 'bukake', 'sound', 'like', 'lovely', '...",mum bukake sound like lovely italian sport car...,"[4384, 21642, 4625, 7780, 11869, 2814, 24601, ...",...,NaN,NaN,[],0.0,0.0,1.0,0.0,54820d30cde04be4ae03b430af47349e,a2a6e1e1cd604504853e54e5c7dacc61,43
177044,"['sentencing', 'humanrights', 'dreams', 'saudi...","[14, 38, 43]",1344398420862242819,"â€˜This sentencing, while partially suspended, s...","['LoujainAlHathloul', 'HumanRights']","['Saudi', 'Saudi_Arabia']",['https://twitter.com/amnesty/status/134383538...,"['sentencing', 'partially', 'suspended', 'crue...",sentencing partially suspended cruelty saudi a...,"[1901, 11075, 4369, 18048, 16176, 15437, 9316,...",...,NaN,NaN,[],1.0,0.0,0.0,0.0,87223ce9b122422f9e9c405ca113e059,0032d16257f148ed8fc078aceef0432f,14
177059,"['um', 'years', 'uk', 'benefits', 'eu', 'dos',...","[18, 17, 29]",1344592142266736641,"Um dos principais objetivos do #Brexit.""EU mig...",['Brexit'],['UK'],['http://www.dailymail.co.uk/news/article-9097...,"['principais', 'objetivos', 'brexiteu', 'migra...",principais objetivos brexiteu migrant able cla...,"[1187, 14267, 20314, 13987, 22425, 16045, 1118...",...,NaN,NaN,[],1.0,1.0,1.0,0.0,a8beb768660c4897a17f9d7823db3a43,de0e0147bfd94b92b37359338a4e76ea,18

In [25]:
df.loc[105]

tokens               ['retirement', 'earn', 'gangsters', 'make', 'w...
topics                                                    [18, 10, 45]
id                                                 1231355568402685953
texts                Bozoâ€™s charlatan gangsters will make us work a...
hashtags                                           ['youvebeenwarned']
entities                                                      ['Bozo']
urls                 ['https://www.theguardian.com/politics/2020/fe...
processed_tokens     ['bozo', 'charlatan', 'gangster', 'work', 'ret...
processed_text       bozo charlatan gangster work retirement earn p...
processed_tm          [24060, 17085, 20373, 21729, 8002, 12872, 23667]
text_processed       bozo charlatan gangster u work retirement earn...
pred_sentiment                                                       1
hatespeech_pred                                                      2
hatespeech_label                                            hatespeech
sentiment_label                                                neutral
Year                                                              2020
author_id                                                    493239913
Month                                                                2
Day                                                                 22
entity_0             {'mention': 'bozos', 'id': 326818, 'start_pos'...
entity_1                                                           NaN
entity_2                                                           NaN
entity_3                                                           NaN
entity_4                                                           NaN
entity_5                                                           NaN
entity_6                                                           NaN
entity_7                                                           NaN
entity_8                                                           NaN
entity_9                                                           NaN
entity_10                                                          NaN
entity_11                                                          NaN
entity_12                                                          NaN
entity_13                                                          NaN
entity_14                                                          NaN
entity_15                                                          NaN
entity_16                                                          NaN
entity_17                                                          NaN
entity_18                                                          NaN
entity_19                                                          NaN
entity_20                                                          NaN
entity_21                                                          NaN
country_code                                                        GB
lon                                                               -1.5
lat                                                           53.53333
created_at                                    2020-02-22T23:10:19.000Z
place_fullname0                                      Barnsley, England
pred_country_name                                                  GBR
consistent                                                        True
place_id                                              3a11764486a570c0
place_fullname                                       Barnsley, England
twi_long                                                           NaN
twi_lat                                                            NaN
user_mentions                                                       []
retweet_count                                                      1.0
reply_count                                                        0.0
like_count                                                         0.0
quote_count                                                        0.0
id_gen                                6c65e67c6b654de58c498eeb2b326ea8
author_id_gen                         351365e7afa547d8ad0255871bd9480a
prim_topic                                                          18
Name: 105, dtype: object

In [23]:
df[(~df['lon'].isnull()) & (df['twi_long'].isnull())] #60886

,tokens,topics,id,texts,hashtags,entities,urls,processed_tokens,processed_text,processed_tm,...,twi_long,twi_lat,user_mentions,retweet_count,reply_count,like_count,quote_count,id_gen,author_id_gen,prim_topic
105,"['retirement', 'earn', 'gangsters', 'make', 'w...","[18, 10, 45]",1231355568402685953,Bozoâ€™s charlatan gangsters will make us work a...,['youvebeenwarned'],['Bozo'],['https://www.theguardian.com/politics/2020/fe...,"['bozo', 'charlatan', 'gangster', 'work', 'ret...",bozo charlatan gangster work retirement earn p...,"[24060, 17085, 20373, 21729, 8002, 12872, 23667]",...,NaN,NaN,[],1.0,0.0,0.0,0.0,6c65e67c6b654de58c498eeb2b326ea8,351365e7afa547d8ad0255871bd9480a,18
114,"['anger', 'hate', 'stop', 'teach', 'spread', '...","[0, 48, 43]",1110529520661078017,@rauddinka @SyedaSaba12 @bashirahmed1342 @Gand...,"['QURAN', 'Islamispeace', 'HUMANITY']",[],['https://twitter.com/zuk60/status/11105295206...,"['hate', 'anger', 'group', 'quran', 'pak', 'do...",hate anger group quran pak doe teach nonsense ...,"[3011, 498, 18883, 13569, 23934, 9137, 18424, ...",...,NaN,NaN,"['rauddinka', 'SyedaSaba12', 'bashirahmed1342'...",0.0,2.0,2.0,0.0,17be95b4e5414e3bb57c9243a8689900,f23b18843d214e339afd1090d945bf99,0
115,"['amp', 'years', 'laws', 'pakistan', 'internat...","[48, 22, 40]",1141587633832939520,@kadar_k @AliaMallick @MrNaassir @mohsinmalvi1...,['Syria'],"['Oliver_Cromwell', 'Pakistan']",[],"['oliver_cromwell', 'exhumed', 'hanged', 'deca...",oliver_cromwell exhumed hanged decapitated yea...,"[23142, 350, 5718, 18305, 20373, 6584, 9644, 1...",...,NaN,NaN,"['kadar_k', 'MrNaassir', 'mohsinmalvi19', 'ily...",0.0,1.0,1.0,0.0,09c5af09d11b46edb125ee1da1e99089,f23b18843d214e339afd1090d945bf99,48
898,"['good', 'morning', 'lib', 'dems', 'britain', ...","[8, 4, 2]",1132759770866360320,Allen and Umunna will be Lib Dems before Good ...,['EuropeanElection2019'],"['Allen', 'Umunna', 'Dems', 'Britain']",['https://twitter.com/lewis_goodall/status/113...,"['allen', 'umunna', 'lib', 'dems', 'good', 'mo...",allen umunna lib dems good morning britain sta...,"[5007, 11738, 219, 1965, 17344, 19442]",...,NaN,NaN,[],1.0,0.0,1.0,0.0,f600e7bb2ff64b0bb0ce0f6c62ae2027,4ae3be0e2c91470f89f81497a81cbadd,8
899,"['mogg', 'country', 'interesting']","[35, 10, 38]",1132760981707341825,Interesting. Mogg country #EuropeanElection201...,['EuropeanElection2019'],[],['https://twitter.com/BritainElects/status/113...,"['interesting', 'mogg', 'country', 'europeanel...",interesting mogg country europeanelection2019,"[12074, 4505, 8997]",...,NaN,NaN,[],0.0,0.0,1.0,0.0,a815b58d651a41348097f9903092b5e7,4ae3be0e2c91470f89f81497a81cbadd,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177088,"['cares', 'years', 'newyear', 'winning', 'euro...","[48, 40, 34]",1344764305653313542,Not that anyone cares but @zdf are definitely ...,"['NewYear', 'European']",[],[],"['care', 'definitely', 'winning', 'new', 'year...",care definitely winning new year eve entertain...,"[3178, 11850, 5718, 22697, 23623, 9278, 15969]",...,NaN,NaN,['ZDF'],0.0,0.0,1.0,0.0,e021770551744e35b5cbfdc78a8ec513,630edc5da73147c0b70bdef2d0c61560,48
177090,"['leavealighton', 'european', 'proud', 'scotla...","[34, 48, 32]",1344786415004119040,I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...,"['LeaveALightOn', 'ScotlandInEurope', 'IndySco...",[],[],"['proud', 'european', 'leavealighton', 'scotla...",proud european leavealighton scotlandineurope ...,"[22302, 15969, 15826, 24352]",...,NaN,NaN,[],36.0,0.0,44.0,0.0,2018d6ea3285487d9cd1259122af2b46,a639a9f328bc4f8f8de0782341534ec8,34
177091,"['minute', 'wee', 'wi', 'eh', 'tae', 'whit', '...","[48, 7, 32]",1344789100902162433,2021 in a wee minute. And whit are you going t...,"['DissolveTheUnion', 'IndyScotland21', 'Scotla...",[],[],"['wee', 'minute', 'whit', 'going', 'tae', 'dae...",wee minute whit going tae dae come going disso...,"[6852, 5572, 19052, 15787, 9311, 14631, 23988,...",...,NaN,NaN,[],3.0,2.0,2.0,0.0,0565132d43714278bf7d1cad9e704f66,37b45cb033934c5c975d0c5d37deb106,48
177092,"['iameuropean', 'star', 'heartbroken', 'bye', ...","[8, 48, 17]",1344790546875871237,"Bye bye EU, Iâ€™m am and always will be heartbro...","['BrexitDisaster', 'IAmEuropean']",[],['https://twitter.com/redlibertine/status/1344...,"['bye', 'bye', 'heartbroken', 'star', 'safe', ...",bye bye heartbroken star safe brexitdisaster i...,"[7341, 7341, 13987, 23988, 6714, 3906, 16191, ...",...,NaN,NaN,[],0.0,0.0,4.0,0.0,ea783b5215484c988065dcf9bdd5ec84,e4cab414f2be45f19b73fcc21ab0c997,8
177094,"['scotlandineu', 'pass', 'scotlandineurope']","[48, 10, 12]",1344793429360959491,Pass it on #IndyScotland21 #ScotlandinEU #Scot...,"['IndyScotland21', 'ScotlandinEU', 'ScotlandIn...",[],[],"['pas', 'indyscotland21', 'scotlandineu', 'sco...",pas indyscotland21 scotlandineu scotlandineuro...,"[23636, 2813, 24352]",...,NaN,NaN,[],1.0,0.0,2.0,0.0,66df93d6b0c848e2b9427bd6e137a30a,cee3dba2a4294ef0ae458849a0b08b4c,48

In [18]:
df[~df['place_fullname0'].isnull()] #60886

,tokens,topics,id,texts,hashtags,entities,urls,processed_tokens,processed_text,processed_tm,...,twi_long,twi_lat,user_mentions,retweet_count,reply_count,like_count,quote_count,id_gen,author_id_gen,prim_topic
105,"['retirement', 'earn', 'gangsters', 'make', 'w...","[18, 10, 45]",1231355568402685953,Bozoâ€™s charlatan gangsters will make us work a...,['youvebeenwarned'],['Bozo'],['https://www.theguardian.com/politics/2020/fe...,"['bozo', 'charlatan', 'gangster', 'work', 'ret...",bozo charlatan gangster work retirement earn p...,"[24060, 17085, 20373, 21729, 8002, 12872, 23667]",...,NaN,NaN,[],1.0,0.0,0.0,0.0,6c65e67c6b654de58c498eeb2b326ea8,351365e7afa547d8ad0255871bd9480a,18
114,"['anger', 'hate', 'stop', 'teach', 'spread', '...","[0, 48, 43]",1110529520661078017,@rauddinka @SyedaSaba12 @bashirahmed1342 @Gand...,"['QURAN', 'Islamispeace', 'HUMANITY']",[],['https://twitter.com/zuk60/status/11105295206...,"['hate', 'anger', 'group', 'quran', 'pak', 'do...",hate anger group quran pak doe teach nonsense ...,"[3011, 498, 18883, 13569, 23934, 9137, 18424, ...",...,NaN,NaN,"['rauddinka', 'SyedaSaba12', 'bashirahmed1342'...",0.0,2.0,2.0,0.0,17be95b4e5414e3bb57c9243a8689900,f23b18843d214e339afd1090d945bf99,0
115,"['amp', 'years', 'laws', 'pakistan', 'internat...","[48, 22, 40]",1141587633832939520,@kadar_k @AliaMallick @MrNaassir @mohsinmalvi1...,['Syria'],"['Oliver_Cromwell', 'Pakistan']",[],"['oliver_cromwell', 'exhumed', 'hanged', 'deca...",oliver_cromwell exhumed hanged decapitated yea...,"[23142, 350, 5718, 18305, 20373, 6584, 9644, 1...",...,NaN,NaN,"['kadar_k', 'MrNaassir', 'mohsinmalvi19', 'ily...",0.0,1.0,1.0,0.0,09c5af09d11b46edb125ee1da1e99089,f23b18843d214e339afd1090d945bf99,48
898,"['good', 'morning', 'lib', 'dems', 'britain', ...","[8, 4, 2]",1132759770866360320,Allen and Umunna will be Lib Dems before Good ...,['EuropeanElection2019'],"['Allen', 'Umunna', 'Dems', 'Britain']",['https://twitter.com/lewis_goodall/status/113...,"['allen', 'umunna', 'lib', 'dems', 'good', 'mo...",allen umunna lib dems good morning britain sta...,"[5007, 11738, 219, 1965, 17344, 19442]",...,NaN,NaN,[],1.0,0.0,1.0,0.0,f600e7bb2ff64b0bb0ce0f6c62ae2027,4ae3be0e2c91470f89f81497a81cbadd,8
899,"['mogg', 'country', 'interesting']","[35, 10, 38]",1132760981707341825,Interesting. Mogg country #EuropeanElection201...,['EuropeanElection2019'],[],['https://twitter.com/BritainElects/status/113...,"['interesting', 'mogg', 'country', 'europeanel...",interesting mogg country europeanelection2019,"[12074, 4505, 8997]",...,NaN,NaN,[],0.0,0.0,1.0,0.0,a815b58d651a41348097f9903092b5e7,4ae3be0e2c91470f89f81497a81cbadd,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177088,"['cares', 'years', 'newyear', 'winning', 'euro...","[48, 40, 34]",1344764305653313542,Not that anyone cares but @zdf are definitely ...,"['NewYear', 'European']",[],[],"['care', 'definitely', 'winning', 'new', 'year...",care definitely winning new year eve entertain...,"[3178, 11850, 5718, 22697, 23623, 9278, 15969]",...,NaN,NaN,['ZDF'],0.0,0.0,1.0,0.0,e021770551744e35b5cbfdc78a8ec513,630edc5da73147c0b70bdef2d0c61560,48
177090,"['leavealighton', 'european', 'proud', 'scotla...","[34, 48, 32]",1344786415004119040,I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...,"['LeaveALightOn', 'ScotlandInEurope', 'IndySco...",[],[],"['proud', 'european', 'leavealighton', 'scotla...",proud european leavealighton scotlandineurope ...,"[22302, 15969, 15826, 24352]",...,NaN,NaN,[],36.0,0.0,44.0,0.0,2018d6ea3285487d9cd1259122af2b46,a639a9f328bc4f8f8de0782341534ec8,34
177091,"['minute', 'wee', 'wi', 'eh', 'tae', 'whit', '...","[48, 7, 32]",1344789100902162433,2021 in a wee minute. And whit are you going t...,"['DissolveTheUnion', 'IndyScotland21', 'Scotla...",[],[],"['wee', 'minute', 'whit', 'going', 'tae', 'dae...",wee minute whit going tae dae come going disso...,"[6852, 5572, 19052, 15787, 9311, 14631, 23988,...",...,NaN,NaN,[],3.0,2.0,2.0,0.0,0565132d43714278bf7d1cad9e704f66,37b45cb033934c5c975d0c5d37deb106,48
177092,"['iameuropean', 'star', 'heartbroken', 'bye', ...","[8, 48, 17]",1344790546875871237,"Bye bye EU, Iâ€™m am and always will be heartbro...","['BrexitDisaster', 'IAmEuropean']",[],['https://twitter.com/redlibertine/status/1344...,"['bye', 'bye', 'heartbroken', 'star', 'safe', ...",bye bye heartbroken star safe brexitdisaster i...,"[7341, 7341, 13987, 23988, 6714, 3906, 16191, ...",...,NaN,NaN,[],0.0,0.0,4.0,0.0,ea783b5215484c988065dcf9bdd5ec84,e4cab414f2be45f19b73fcc21ab0c997,8
177094,"['scotlandineu', 'pass', 'scotlandineurope']","[48, 10, 12]",1344793429360959491,Pass it on #IndyScotland21 #ScotlandinEU #Scot...,"['IndyScotland21', 'ScotlandinEU', 'ScotlandIn...",[],[],"['pas', 'indyscotland21', 'scotlandineu', 'sco...",pas indyscotland21 scotlandineu scotlandineuro...,"[23636, 2813, 24352]",...,NaN,NaN,[],1.0,0.0,2.0,0.0,66df93d6b0c848e2b9427bd6e137a30a,cee3dba2a4294ef0ae458849a0b08b4c,48

In [19]:
df[~df['pred_country_name'].isnull()] #74231

,tokens,topics,id,texts,hashtags,entities,urls,processed_tokens,processed_text,processed_tm,...,twi_long,twi_lat,user_mentions,retweet_count,reply_count,like_count,quote_count,id_gen,author_id_gen,prim_topic
105,"['retirement', 'earn', 'gangsters', 'make', 'w...","[18, 10, 45]",1231355568402685953,Bozoâ€™s charlatan gangsters will make us work a...,['youvebeenwarned'],['Bozo'],['https://www.theguardian.com/politics/2020/fe...,"['bozo', 'charlatan', 'gangster', 'work', 'ret...",bozo charlatan gangster work retirement earn p...,"[24060, 17085, 20373, 21729, 8002, 12872, 23667]",...,NaN,NaN,[],1.0,0.0,0.0,0.0,6c65e67c6b654de58c498eeb2b326ea8,351365e7afa547d8ad0255871bd9480a,18
114,"['anger', 'hate', 'stop', 'teach', 'spread', '...","[0, 48, 43]",1110529520661078017,@rauddinka @SyedaSaba12 @bashirahmed1342 @Gand...,"['QURAN', 'Islamispeace', 'HUMANITY']",[],['https://twitter.com/zuk60/status/11105295206...,"['hate', 'anger', 'group', 'quran', 'pak', 'do...",hate anger group quran pak doe teach nonsense ...,"[3011, 498, 18883, 13569, 23934, 9137, 18424, ...",...,NaN,NaN,"['rauddinka', 'SyedaSaba12', 'bashirahmed1342'...",0.0,2.0,2.0,0.0,17be95b4e5414e3bb57c9243a8689900,f23b18843d214e339afd1090d945bf99,0
115,"['amp', 'years', 'laws', 'pakistan', 'internat...","[48, 22, 40]",1141587633832939520,@kadar_k @AliaMallick @MrNaassir @mohsinmalvi1...,['Syria'],"['Oliver_Cromwell', 'Pakistan']",[],"['oliver_cromwell', 'exhumed', 'hanged', 'deca...",oliver_cromwell exhumed hanged decapitated yea...,"[23142, 350, 5718, 18305, 20373, 6584, 9644, 1...",...,NaN,NaN,"['kadar_k', 'MrNaassir', 'mohsinmalvi19', 'ily...",0.0,1.0,1.0,0.0,09c5af09d11b46edb125ee1da1e99089,f23b18843d214e339afd1090d945bf99,48
898,"['good', 'morning', 'lib', 'dems', 'britain', ...","[8, 4, 2]",1132759770866360320,Allen and Umunna will be Lib Dems before Good ...,['EuropeanElection2019'],"['Allen', 'Umunna', 'Dems', 'Britain']",['https://twitter.com/lewis_goodall/status/113...,"['allen', 'umunna', 'lib', 'dems', 'good', 'mo...",allen umunna lib dems good morning britain sta...,"[5007, 11738, 219, 1965, 17344, 19442]",...,NaN,NaN,[],1.0,0.0,1.0,0.0,f600e7bb2ff64b0bb0ce0f6c62ae2027,4ae3be0e2c91470f89f81497a81cbadd,8
899,"['mogg', 'country', 'interesting']","[35, 10, 38]",1132760981707341825,Interesting. Mogg country #EuropeanElection201...,['EuropeanElection2019'],[],['https://twitter.com/BritainElects/status/113...,"['interesting', 'mogg', 'country', 'europeanel...",interesting mogg country europeanelection2019,"[12074, 4505, 8997]",...,NaN,NaN,[],0.0,0.0,1.0,0.0,a815b58d651a41348097f9903092b5e7,4ae3be0e2c91470f89f81497a81cbadd,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177090,"['leavealighton', 'european', 'proud', 'scotla...","[34, 48, 32]",1344786415004119040,I'll always be a proud European ðŸ‡ªðŸ‡º #LeaveALigh...,"['LeaveALightOn', 'ScotlandInEurope', 'IndySco...",[],[],"['proud', 'european', 'leavealighton', 'scotla...",proud european leavealighton scotlandineurope ...,"[22302, 15969, 15826, 24352]",...,NaN,NaN,[],36.0,0.0,44.0,0.0,2018d6ea3285487d9cd1259122af2b46,a639a9f328bc4f8f8de0782341534ec8,34
177091,"['minute', 'wee', 'wi', 'eh', 'tae', 'whit', '...","[48, 7, 32]",1344789100902162433,2021 in a wee minute. And whit are you going t...,"['DissolveTheUnion', 'IndyScotland21', 'Scotla...",[],[],"['wee', 'minute', 'whit', 'going', 'tae', 'dae...",wee minute whit going tae dae come going disso...,"[6852, 5572, 19052, 15787, 9311, 14631, 23988,...",...,NaN,NaN,[],3.0,2.0,2.0,0.0,0565132d43714278bf7d1cad9e704f66,37b45cb033934c5c975d0c5d37deb106,48
177092,"['iameuropean', 'star', 'heartbroken', 'bye', ...","[8, 48, 17]",1344790546875871237,"Bye bye EU, Iâ€™m am and always will be heartbro...","['BrexitDisaster', 'IAmEuropean']",[],['https://twitter.com/redlibertine/status/1344...,"['bye', 'bye', 'heartbroken', 'star', 'safe', ...",bye bye heartbroken star safe brexitdisaster i...,"[7341, 7341, 13987, 23988, 6714, 3906, 16191, ...",...,NaN,NaN,[],0.0,0.0,4.0,0.0,ea783b5215484c988065dcf9bdd5ec84,e4cab414f2be45f19b73fcc21ab0c997,8
177093,"['amp', 'ahead', 'europe', 'hour', 'allowing',...","[4, 40, 18]",1344791154005573632,As #Europe is one hour ahead of #Britain they ...,"['Europe', 'Britain', 'celebrating', 'NewYear'...",[],[],"['europe', 'hour', 'ahead', 'britain', 'celebr...",europe hour ahead britain celebrating newyear ...,"[2878, 2885, 2530, 17344, 21333, 9278, 24558, ...",...,NaN,NaN,['Kevin_Maguire'],0.0,0.0,1.0,0.0,918058469e7d4b8f9674c3dc60383957,53dee5c37f3b4b05b48a29cb16c0bbf0,4
177094,"['scotlandineu', 'pass', 'scotlandineurope']","[48, 10, 12]",1344793429360959491,Pass it on #IndyScotland21 #ScotlandinEU #Scot...,"['IndyScotland21', 'ScotlandinEU', 'ScotlandIn...",[],[],"['pas', 'indyscotland21', 'scotlandineu', 'sco...",pas indyscotland21 scotlandineu scotlandineuro...,"[23636, 2813, 24352]",...,NaN,NaN,[],1.0,0.0,2.0,0.0,66df93d6b0c848e2b9427bd6e137a30a,cee3dba2a4294ef0ae458849a0b08b4c,48

In [8]:
unemployment_rate.to_dict()

{'AT': {2013: 5.4,
  2014: 5.6,
  2015: 5.7,
  2016: 6.0,
  2017: 5.5,
  2018: 4.9,
  2019: 4.5,
  2020: 5.4},
 'CH': {2013: 4.8,
  2014: 4.9,
  2015: 4.8,
  2016: 5.0,
  2017: 4.8,
  2018: 4.7,
  2019: 4.4,
  2020: 4.8},
 'DE': {2013: 5.2,
  2014: 5.0,
  2015: 4.6,
  2016: 4.1,
  2017: 3.8,
  2018: 3.4,
  2019: 3.1,
  2020: 3.8},
 'ES': {2013: 26.1,
  2014: 24.5,
  2015: 22.1,
  2016: 19.6,
  2017: 17.2,
  2018: 15.3,
  2019: 14.1,
  2020: 15.5},
 'FR': {2013: 10.3,
  2014: 10.3,
  2015: 10.4,
  2016: 10.1,
  2017: 9.4,
  2018: 9.0,
  2019: 8.4,
  2020: 8.0},
 'HU': {2013: 10.2,
  2014: 7.7,
  2015: 6.8,
  2016: 5.1,
  2017: 4.2,
  2018: 3.7,
  2019: 3.4,
  2020: 4.3},
 'IT': {2013: 12.2,
  2014: 12.7,
  2015: 11.9,
  2016: 11.7,
  2017: 11.2,
  2018: 10.6,
  2019: 10.0,
  2020: 9.2},
 'NL': {2013: 7.3,
  2014: 7.4,
  2015: 6.9,
  2016: 6.0,
  2017: 4.9,
  2018: 3.8,
  2019: 3.4,
  2020: 3.8},
 'PL': {2013: 10.3,
  2014: 9.0,
  2015: 7.5,
  2016: 6.2,
  2017: 4.9,
  2018: 3.9,
  2019: 3.3,
  2020: 3.2},
 'SE': {2013: 8.1,
  2014: 8.0,
  2015: 7.4,
  2016: 7.0,
  2017: 6.7,
  2018: 6.4,
  2019: 6.8,
  2020: 8.3},
 'UK': {2013: 7.5,
  2014: 6.1,
  2015: 5.3,
  2016: 4.8,
  2017: 4.3,
  2018: 4.0,
  2019: 3.8,
  2020: 4.9}}